/**
 * Paralives Hub — canonical、OG、Twitter、sitemap 使用此域名。
 * @see https://paralives.wiki
 */
export const seoConfig = {
  domain: 'paralives.wiki',
  fullDomain: 'https://paralives.wiki',
  siteName: 'Paralives Wiki',
  /** 分享图绝对 URL；可替换为 https://paralives.wiki/images/og-default.jpg */
  defaultOgImage: '/images/logo.webp',
  defaults: {
    title: 'Paralives — Game Wiki, Guides, Mods, Simulator & Map',
    description:
      'Complete Paralives hub: 11-topic wiki with icons, walkthroughs, mods library, EA roadmap, town map, simulator tools, and start guide with system requirements.',
    keywords:
      'Paralives, Paralives game, Paralives wiki, Paralives guides, Paralives mods, Paralives simulator, Paralives release date, Paralives Steam, Early Access',
    author: 'Paralives Wiki',
    type: 'website',
  },
  priorities: {
    home: 1.0,
    start: 0.95,
    wiki: 0.92,
    'wiki-talents': 0.85,
    'wiki-vibes': 0.85,
    'wiki-skills': 0.85,
    'wiki-traits': 0.85,
    'wiki-emotions': 0.85,
    'wiki-needs-wants': 0.85,
    'wiki-parafolks': 0.85,
    'wiki-build-tools': 0.85,
    'wiki-careers': 0.85,
    'wiki-relationships': 0.85,
    'wiki-modding': 0.85,
    guides: 0.9,
    'guide-detail': 0.8,
    mods: 0.88,
    'mod-detail': 0.75,
    updates: 0.9,
    simulator: 0.88,
    'simulator-feature-filter': 0.82,
    'simulator-trait-points': 0.82,
    'simulator-color-palette': 0.82,
    'simulator-session-roll': 0.82,
    map: 0.9,
    'legal-privacy': 0.35,
    'legal-terms': 0.35,
    'legal-copyright': 0.35,
    'legal-about': 0.45,
    'legal-contact': 0.45,
  },
  changefreq: {
    home: 'weekly',
    start: 'weekly',
    wiki: 'weekly',
    'wiki-talents': 'weekly',
    'wiki-vibes': 'weekly',
    'wiki-skills': 'weekly',
    'wiki-traits': 'weekly',
    'wiki-emotions': 'weekly',
    'wiki-needs-wants': 'weekly',
    'wiki-parafolks': 'weekly',
    'wiki-build-tools': 'weekly',
    'wiki-careers': 'weekly',
    'wiki-relationships': 'weekly',
    'wiki-modding': 'weekly',
    guides: 'weekly',
    'guide-detail': 'monthly',
    mods: 'weekly',
    'mod-detail': 'monthly',
    updates: 'weekly',
    simulator: 'weekly',
    'simulator-feature-filter': 'monthly',
    'simulator-trait-points': 'monthly',
    'simulator-color-palette': 'monthly',
    'simulator-session-roll': 'monthly',
    map: 'weekly',
    'legal-privacy': 'yearly',
    'legal-terms': 'yearly',
    'legal-copyright': 'yearly',
    'legal-about': 'yearly',
    'legal-contact': 'yearly',
  },
}
